name: CI

on: [push, pull_request]

jobs:
  Rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
        alchemy:
          - main
        solidus:
          - "3.2"
          - "3.3"
    env:
      ALCHEMY_VERSION: ${{ matrix.alchemy }}
      SOLIDUS_VERSION: ${{ matrix.solidus }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run tests
        run: bundle exec rake
