name: CI

on: [push, pull_request]

jobs:
  Rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
        alchemy:
          - "7.2-stable"
          - "7.3-stable"
        solidus:
          - "v4.1"
          - "v4.2"
          - "v4.3"
          - "v4.4"
    env:
      ALCHEMY_VERSION: ${{ matrix.alchemy }}
      SOLIDUS_BRANCH: ${{ matrix.solidus }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Prepare tests
        run: bundle exec rake test_setup
      - name: Run tests
        run: bundle exec rspec
