name: CI

on: [push, pull_request]

jobs:
  Rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        alchemy:
          - "7.0.0"
        solidus:
          - "4.0"
          - "4.1"
          - "4.2"
    env:
      ALCHEMY_VERSION: ${{ matrix.alchemy }}
      SOLIDUS_VERSION: ${{ matrix.solidus }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare tests
        run: bundle exec rake test_setup
      - name: Run tests
        run: bundle exec rspec
